import Hero from "@/components/Hero";
import { client } from "@/utils/client";
import { siteSettingsQuery } from "@/utils/queries";
import Head from "next/head";
import Image from "next/image";

export default function Home({ settings }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen">
        <section className="w-full h-screen">
          <h1 className="py-3 font-bold text-center text-white text-9xl font-melodrama text-heroName">
            {settings.title}
          </h1>
        </section>
      </main>
    </>
  );
}

export async function getStaticProps() {
  const settings = await client.fetch(siteSettingsQuery());

  return {
    props: {
      settings,
    },
  };
}
